project:
  type: website
  output-dir: docs/

website:
  title: "IOC"
  # site-url: https://inforbio.github.io/
  favicon: images/logoInforBio_fond_blanc.png
  
    
  navbar:
    logo: images/logoInforBio_fond_blanc.png
    # right:
    #   - href: index.qmd
    #     text: "About IOC"
    left: 
      - text: "Calendar & Info"
        href: ioc_r_info.qmd
      - text: "Slides & Excercises"
        href: ioc_r_toc.qmd
        menu: 
          - text: "Week 1 - Slides"
            href: docs/r_slides_week01.html
          - text: "Week 1 - Excercises"
            href: r_week1.qmd
          # - text: "IOC scRNAseq"
          #   href: ioc_scrnaseq.qmd
      # - text: "News"
      #   href: news.qmd
      - icon: github
        href: https://github.com/InforBio/InforBio.github.io


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



