---
title: "IOC R Training Information"
---

Welcome to the IOC R Training!
This page contains all the essential details for the training.
Please bookmark this page for quick access.

## Calendar

#### **French Group**

- Starts from: Wednesday, 8th January 2025  
- Time slots: **Wednesdays 9:30 am – 12:00 pm**
- Location: Online (Zoom link will be shared prior to the session by email)
- Provisional Schedule:  

  | **Week**       | **Session**          | **Date**         | **Time**           |
  |----------------|----------------------|------------------|--------------------|
  | Week 1         | Kickstart with R: Your Gateway to Data Science       |  8th January  | 9:30 am – 12:00 pm |
  | Week 2         | Data Foundations: Vectors and Matrices               | 15th January  | 9:30 am – 12:00 pm |
  | Week 3         | More Complex Data Structures: Lists and Data Frames  | 22nd January  | 9:30 am – 12:00 pm |
  | Week 4         | Building Logic: Operators, Conditions, and Functions | 29th January  | 9:30 am – 12:00 pm |
  | Week 5         | Graphing with {`ggplot2`}                            |  5th February | 9:30 am – 12:00 pm |
  | Week 6         | R-fresh: Revisiting the Essentials                   | 12th February | 9:30 am – 12:00 pm |
  | Week 7         | Smart Shortcuts: Mastering the `apply` Family        |  5th March    | 9:30 am – 12:00 pm |
  | Week 8         | Tidy Your Data: Exploring {`tidyr`} and {`dplyr`}    | 12th March    | 9:30 am – 12:00 pm |
  | Week 9         | String Tricks & Final Review                         | 19nd March    | 9:30 am – 12:00 pm |
  | Week 10        | Your project presentation                            | TBD           | TBD |


#### **English Group**

- Starts from: Monday, 13th January 2025  
- Time slots: **Mondays 9:30 am – 12:00 pm**  
- Location: Online (Zoom link will be shared prior to the session by email)
- Provisional Schedule:  

  | **Week**       | **Session**          | **Date**         | **Time**           |
  |----------------|----------------------|------------------|--------------------|
  | Week 1         | Kickstart with R: Your Gateway to Data Science       | 13th January  | 9:30 am – 12:00 pm |
  | Week 2         | Data Foundations: Vectors and Matrices               | 20th January  | 9:30 am – 12:00 pm |
  | Week 3         | More Complex Data Structures: Lists and Data Frames  | 27th January  | 9:30 am – 12:00 pm |
  | Week 4         | Building Logic: Operators, Conditions, and Functions |  3rd February | 9:30 am – 12:00 pm |
  | Week 5         | Graphing with {`ggplot2`}                            | 10th February | 9:30 am – 12:00 pm |
  | Week 6         | R-fresh: Revisiting the Essentials                   |  3rd March    | 9:30 am – 12:00 pm |
  | Week 7         | Smart Shortcuts: Mastering the `apply` Family        | 10th March    | 9:30 am – 12:00 pm |
  | Week 8         | Tidy Your Data: Exploring {`tidyr`} and {`dplyr`}    | 17th March    | 9:30 am – 12:00 pm |
  | Week 9         | String Tricks & Final Review                         | 24nd March    | 9:30 am – 12:00 pm |
  | Week 10        | Your project presentation                            | TBD           | TBD |
  

## Recommended Readings

- [R for Data Science](https://r4ds.had.co.nz) by Hadley Wickham
- [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) by Garrett Grolemund 
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2.tidyverse.org) by Hadley Wickham 
- [YaRrr! The Pirate’s Guide to R](https://bookdown.org/ndphillips/YaRrr/) by Nathaniel D. Phillips
- [CRAN R Documentation](https://cran.r-project.org/)

